<?php

namespace Application\ChiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->_em->createQuery('SELECT c FROM ChiaBundle:Category c ORDER BY c.name')
            ->getArrayResult();
    }

    public function getCategoryOptions()
    {
        $categories = $this->_em->createQuery('SELECT c FROM ChiaBundle:Category c ORDER BY c.name')
            ->getArrayResult();
        $category_choices = array();
        foreach ($categories as $category) {
            $category_choices[$category['id']] = $category['name'];
        }
        return $category_choices;
    }
}
