Application\ChiaBundle\Entity\Note:
  type: entity
  table: null
  repositoryClass: Application\ChiaBundle\Entity\NoteRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    verb: # created by, cancelled, won
      type: string(255)
    changes:
      type: string(255)
      nullable: true
    note:
      type: string
      length: null
      nullable: true
    created_at:
      type: datetime
    updated_at:
      type: datetime
  manyToOne:
    project:
      targetEntity: Application\ChiaBundle\Entity\Project
      inversedBy: notes
    created_by:
      targetEntity: Application\ChiaBundle\Entity\User
      inversedBy: notes
  lifecycleCallbacks:
    prePersist: [ doStuffOnPrePersist ]
    preUpdate: [ doStuffOnPreUpdate ]
