Application\ChiaBundle\Entity\Email:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    email:
      type: string(100)
  manyToOne:
    contact:
      targetEntity: Contact
      inversedBy: emails
