Application\ChiaBundle\Entity\Permission:
  type: entity
  table: null
  repositoryClass: Application\ChiaBundle\Entity\PermissionRepository
  lifecycleCallbacks:
    prePersist: [ doStuffOnPrePersist ]
    preUpdate: [ doStuffOnPreUpdate ]
