Application\ChiaBundle\Entity\Category:
  type: entity
  table: null
  repositoryClass: Application\ChiaBundle\Entity\CategoryRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string(100)
  oneToMany:
    projects:
      targetEntity: Project
      mappedBy: category
